# Generated by Django 4.0.4 on 2022-05-07 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0004_transactions_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='user_balance',
        ),
    ]
