# Generated by Django 4.0.4 on 2022-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0007_transactions_user_balance_alter_transactions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='balance_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
