# Generated by Django 4.0.4 on 2022-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0009_alter_transactions_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user_balance',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
