# Generated by Django 4.0.4 on 2022-05-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0010_alter_transactions_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='user_balance',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='iet.transactions'),
        ),
    ]
