# Generated by Django 4.0.4 on 2022-05-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0011_remove_transactions_user_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transactions',
            name='closing_balance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
