# Generated by Django 4.0.4 on 2022-05-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0012_remove_userbalance_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='date',
        ),
        migrations.AddField(
            model_name='transactions',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
