# Generated by Django 4.0.4 on 2022-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0013_remove_transactions_date_transactions_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
