# Generated by Django 4.0.4 on 2022-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0014_transactions_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
