# Generated by Django 4.0.4 on 2022-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0015_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
