# Generated by Django 4.0.4 on 2022-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iet', '0016_alter_transactions_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
